-- generated by asdl2/generate_schema_boot.lua
local Boot = require("asdl2.asdl2_boot")

return Boot.build({
    phases = {
        Asdl2Catalog = {
            records = {
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "BuiltinTypeRef",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "VariantHeader",
                        },
                        {
                            list = true,
                            name = "fields",
                            optional = false,
                            type = "Field",
                        },
                        {
                            list = false,
                            name = "unique_flag",
                            optional = false,
                            type = "boolean",
                        },
                    },
                    name = "Constructor",
                    unique = true,
                },
                {
                    fields = {},
                    name = "ExactlyOne",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "ExternalTypeRef",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "type_ref",
                            optional = false,
                            type = "TypeRef",
                        },
                        {
                            list = false,
                            name = "cardinality",
                            optional = false,
                            type = "Cardinality",
                        },
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "Field",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "query_name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "target",
                            optional = false,
                            type = "LookupTarget",
                        },
                    },
                    name = "LookupEntry",
                    unique = true,
                },
                {
                    fields = {},
                    name = "Many",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "scope",
                            optional = false,
                            type = "Scope",
                        },
                        {
                            list = true,
                            name = "definitions",
                            optional = false,
                            type = "Definition",
                        },
                    },
                    name = "ModuleDef",
                    unique = false,
                },
                {
                    fields = {},
                    name = "Optional",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "ProductHeader",
                        },
                        {
                            list = true,
                            name = "fields",
                            optional = false,
                            type = "Field",
                        },
                        {
                            list = false,
                            name = "unique_flag",
                            optional = false,
                            type = "boolean",
                        },
                    },
                    name = "ProductDef",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "class_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "ctor",
                            optional = false,
                            type = "Asdl2Lowered.CtorFamily",
                        },
                    },
                    name = "ProductHeader",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "ProductHeader",
                        },
                    },
                    name = "ProductTarget",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "ProductHeader",
                        },
                    },
                    name = "ProductTargetRef",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = true,
                            name = "lookups",
                            optional = false,
                            type = "LookupEntry",
                        },
                    },
                    name = "Scope",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "root_scope",
                            optional = false,
                            type = "Scope",
                        },
                        {
                            list = true,
                            name = "definitions",
                            optional = false,
                            type = "Definition",
                        },
                    },
                    name = "Spec",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "SumHeader",
                        },
                        {
                            list = true,
                            name = "constructors",
                            optional = false,
                            type = "Constructor",
                        },
                        {
                            list = true,
                            name = "attribute_fields",
                            optional = false,
                            type = "Field",
                        },
                    },
                    name = "SumDef",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "family_id",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "SumHeader",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "SumHeader",
                        },
                        {
                            list = true,
                            name = "variants",
                            optional = false,
                            type = "VariantHeader",
                        },
                    },
                    name = "SumTarget",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "SumHeader",
                        },
                        {
                            list = true,
                            name = "variants",
                            optional = false,
                            type = "VariantHeader",
                        },
                    },
                    name = "SumTargetRef",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "parent_fqname",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "kind_name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "class_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "family_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "variant_tag",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "ctor",
                            optional = false,
                            type = "Asdl2Lowered.CtorFamily",
                        },
                    },
                    name = "VariantHeader",
                    unique = true,
                },
            },
            sums = {
                {
                    name = "Cardinality",
                    variants = {
                        "ExactlyOne",
                        "Optional",
                        "Many",
                    },
                },
                {
                    name = "Definition",
                    variants = {
                        "ModuleDef",
                        "ProductDef",
                        "SumDef",
                    },
                },
                {
                    name = "LookupTarget",
                    variants = {
                        "ProductTarget",
                        "SumTarget",
                    },
                },
                {
                    name = "TypeRef",
                    variants = {
                        "BuiltinTypeRef",
                        "ExternalTypeRef",
                        "ProductTargetRef",
                        "SumTargetRef",
                    },
                },
            },
        },
        Asdl2Lowered = {
            records = {
                {
                    fields = {},
                    name = "AnyCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "BuiltinCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "cache_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "kind",
                            optional = false,
                            type = "CacheKind",
                        },
                        {
                            list = false,
                            name = "key_arity",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "owner_fqname",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "CacheSlot",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "cache_id",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "CacheSlotRef",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "class_id",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "ExactClassCheck",
                    unique = false,
                },
                {
                    fields = {},
                    name = "ExactlyOne",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "ExternalCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "type_name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "arena_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "handle_field",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "handle_ctype",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "check",
                            optional = false,
                            type = "CheckSpec",
                        },
                    },
                    name = "HandleListField",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "type_name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "cardinality",
                            optional = false,
                            type = "ScalarCardinality",
                        },
                        {
                            list = false,
                            name = "arena_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "handle_field",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "handle_ctype",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "check",
                            optional = false,
                            type = "CheckSpec",
                        },
                    },
                    name = "HandleScalarField",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "type_name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "c_name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "c_type",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "check",
                            optional = false,
                            type = "CheckSpec",
                        },
                    },
                    name = "InlineField",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "arena_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "target",
                            optional = false,
                            type = "CheckSpec",
                        },
                        {
                            list = false,
                            name = "handle_ctype",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "ListArenaSlot",
                    unique = false,
                },
                {
                    fields = {},
                    name = "NoCacheRef",
                    unique = false,
                },
                {
                    fields = {},
                    name = "NullaryCtor",
                    unique = false,
                },
                {
                    fields = {},
                    name = "Optional",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "field_count",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "ProductCtor",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "Asdl2Catalog.ProductHeader",
                        },
                        {
                            list = false,
                            name = "cache",
                            optional = false,
                            type = "CacheRef",
                        },
                        {
                            list = true,
                            name = "fields",
                            optional = false,
                            type = "Field",
                        },
                    },
                    name = "ProductRecord",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "arena_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "target",
                            optional = false,
                            type = "CheckSpec",
                        },
                        {
                            list = false,
                            name = "handle_ctype",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "ScalarArenaSlot",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = true,
                            name = "records",
                            optional = false,
                            type = "Record",
                        },
                        {
                            list = true,
                            name = "sums",
                            optional = false,
                            type = "Sum",
                        },
                        {
                            list = true,
                            name = "arenas",
                            optional = false,
                            type = "ArenaSlot",
                        },
                        {
                            list = true,
                            name = "caches",
                            optional = false,
                            type = "CacheSlot",
                        },
                    },
                    name = "Schema",
                    unique = true,
                },
                {
                    fields = {},
                    name = "SingletonKind",
                    unique = false,
                },
                {
                    fields = {},
                    name = "StructuralKind",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "Asdl2Catalog.SumHeader",
                        },
                        {
                            list = true,
                            name = "variants",
                            optional = false,
                            type = "Asdl2Catalog.VariantHeader",
                        },
                    },
                    name = "Sum",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "family_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = true,
                            name = "variant_tags",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "SumFamilyCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "field_count",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "VariantCtor",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "Asdl2Catalog.VariantHeader",
                        },
                        {
                            list = false,
                            name = "cache",
                            optional = false,
                            type = "CacheRef",
                        },
                        {
                            list = true,
                            name = "fields",
                            optional = false,
                            type = "Field",
                        },
                    },
                    name = "VariantRecord",
                    unique = false,
                },
            },
            sums = {
                {
                    name = "ArenaSlot",
                    variants = {
                        "ScalarArenaSlot",
                        "ListArenaSlot",
                    },
                },
                {
                    name = "CacheKind",
                    variants = {
                        "SingletonKind",
                        "StructuralKind",
                    },
                },
                {
                    name = "CacheRef",
                    variants = {
                        "NoCacheRef",
                        "CacheSlotRef",
                    },
                },
                {
                    name = "CheckSpec",
                    variants = {
                        "AnyCheck",
                        "BuiltinCheck",
                        "ExternalCheck",
                        "ExactClassCheck",
                        "SumFamilyCheck",
                    },
                },
                {
                    name = "CtorFamily",
                    variants = {
                        "NullaryCtor",
                        "ProductCtor",
                        "VariantCtor",
                    },
                },
                {
                    name = "Field",
                    variants = {
                        "InlineField",
                        "HandleScalarField",
                        "HandleListField",
                    },
                },
                {
                    name = "Record",
                    variants = {
                        "ProductRecord",
                        "VariantRecord",
                    },
                },
                {
                    name = "ScalarCardinality",
                    variants = {
                        "ExactlyOne",
                        "Optional",
                    },
                },
            },
        },
        Asdl2LuaJIT = {
            records = {
                {
                    fields = {},
                    name = "AnyListCheck",
                    unique = false,
                },
                {
                    fields = {},
                    name = "AnyOptionalCheck",
                    unique = false,
                },
                {
                    fields = {},
                    name = "AnyScalarCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "BuiltinListCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "BuiltinOptionalCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "BuiltinScalarCheck",
                    unique = false,
                },
                {
                    fields = {},
                    name = "CallableExport",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "class_id",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "ExactClassListCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "class_id",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "ExactClassOptionalCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "class_id",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "ExactClassScalarCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "ExternalListCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "ExternalOptionalCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "ExternalScalarCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = true,
                            name = "arg_ixs",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "cache",
                            optional = false,
                            type = "CachePlan",
                        },
                    },
                    name = "GenericCtor",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = true,
                            name = "field_ixs",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "HandleAccess",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "handle_field",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "arena_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "handle_ctype",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "check",
                            optional = false,
                            type = "CheckPlan",
                        },
                        {
                            list = false,
                            name = "display_type",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "HandleListFieldPlan",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "arg1_ix",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "HandleScalar1CtorNoCache",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "handle_field",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "arena_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "handle_ctype",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "check",
                            optional = false,
                            type = "CheckPlan",
                        },
                        {
                            list = false,
                            name = "display_type",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "HandleScalarFieldPlan",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "arg1_ix",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "Inline1CtorNoCache",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "cache_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "arg1_ix",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "Inline1CtorStructuralCache",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "arg1_ix",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "arg2_ix",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "Inline2CtorNoCache",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "cache_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "arg1_ix",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "arg2_ix",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "Inline2CtorStructuralCache",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "slot_name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "c_type",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "check",
                            optional = false,
                            type = "CheckPlan",
                        },
                        {
                            list = false,
                            name = "display_type",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "InlineFieldPlan",
                    unique = false,
                },
                {
                    fields = {},
                    name = "InlineOnlyAccess",
                    unique = false,
                },
                {
                    fields = {},
                    name = "NoCachePlan",
                    unique = false,
                },
                {
                    fields = {},
                    name = "NullaryCtorNoCache",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "cache_id",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "NullaryCtorSingletonCache",
                    unique = false,
                },
                {
                    fields = {},
                    name = "NullaryValueExport",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "Asdl2Catalog.ProductHeader",
                        },
                        {
                            list = false,
                            name = "ctype_name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = true,
                            name = "fields",
                            optional = false,
                            type = "FieldPlan",
                        },
                        {
                            list = false,
                            name = "cache",
                            optional = false,
                            type = "CachePlan",
                        },
                        {
                            list = false,
                            name = "access",
                            optional = false,
                            type = "AccessPlan",
                        },
                        {
                            list = false,
                            name = "ctor",
                            optional = false,
                            type = "CtorPlan",
                        },
                        {
                            list = false,
                            name = "export",
                            optional = false,
                            type = "ExportPlan",
                        },
                    },
                    name = "ProductClass",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = true,
                            name = "records",
                            optional = false,
                            type = "RecordClass",
                        },
                        {
                            list = true,
                            name = "sums",
                            optional = false,
                            type = "SumClass",
                        },
                        {
                            list = true,
                            name = "arenas",
                            optional = false,
                            type = "Asdl2Lowered.ArenaSlot",
                        },
                        {
                            list = true,
                            name = "caches",
                            optional = false,
                            type = "Asdl2Lowered.CacheSlot",
                        },
                    },
                    name = "Schema",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "cache_id",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "SingletonCachePlan",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "cache_id",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "key_arity",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "StructuralCachePlan",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "Asdl2Catalog.SumHeader",
                        },
                        {
                            list = true,
                            name = "variants",
                            optional = false,
                            type = "Asdl2Catalog.VariantHeader",
                        },
                    },
                    name = "SumClass",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "family_id",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "SumFamilyListCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "family_id",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "SumFamilyOptionalCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "family_id",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "SumFamilyScalarCheck",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "header",
                            optional = false,
                            type = "Asdl2Catalog.VariantHeader",
                        },
                        {
                            list = false,
                            name = "ctype_name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = true,
                            name = "fields",
                            optional = false,
                            type = "FieldPlan",
                        },
                        {
                            list = false,
                            name = "cache",
                            optional = false,
                            type = "CachePlan",
                        },
                        {
                            list = false,
                            name = "access",
                            optional = false,
                            type = "AccessPlan",
                        },
                        {
                            list = false,
                            name = "ctor",
                            optional = false,
                            type = "CtorPlan",
                        },
                        {
                            list = false,
                            name = "export",
                            optional = false,
                            type = "ExportPlan",
                        },
                    },
                    name = "VariantClass",
                    unique = false,
                },
            },
            sums = {
                {
                    name = "AccessPlan",
                    variants = {
                        "InlineOnlyAccess",
                        "HandleAccess",
                    },
                },
                {
                    name = "CachePlan",
                    variants = {
                        "NoCachePlan",
                        "SingletonCachePlan",
                        "StructuralCachePlan",
                    },
                },
                {
                    name = "CheckPlan",
                    variants = {
                        "AnyScalarCheck",
                        "AnyOptionalCheck",
                        "AnyListCheck",
                        "BuiltinScalarCheck",
                        "BuiltinOptionalCheck",
                        "BuiltinListCheck",
                        "ExternalScalarCheck",
                        "ExternalOptionalCheck",
                        "ExternalListCheck",
                        "ExactClassScalarCheck",
                        "ExactClassOptionalCheck",
                        "ExactClassListCheck",
                        "SumFamilyScalarCheck",
                        "SumFamilyOptionalCheck",
                        "SumFamilyListCheck",
                    },
                },
                {
                    name = "CtorPlan",
                    variants = {
                        "NullaryCtorNoCache",
                        "NullaryCtorSingletonCache",
                        "Inline1CtorNoCache",
                        "Inline1CtorStructuralCache",
                        "Inline2CtorNoCache",
                        "Inline2CtorStructuralCache",
                        "HandleScalar1CtorNoCache",
                        "GenericCtor",
                    },
                },
                {
                    name = "ExportPlan",
                    variants = {
                        "CallableExport",
                        "NullaryValueExport",
                    },
                },
                {
                    name = "FieldPlan",
                    variants = {
                        "InlineFieldPlan",
                        "HandleScalarFieldPlan",
                        "HandleListFieldPlan",
                    },
                },
                {
                    name = "RecordClass",
                    variants = {
                        "ProductClass",
                        "VariantClass",
                    },
                },
            },
        },
        Asdl2Machine = {
            records = {
                {
                    fields = {},
                    name = "NoCache",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "ctor",
                            optional = false,
                            type = "Asdl2Lowered.CtorFamily",
                        },
                        {
                            list = false,
                            name = "cache",
                            optional = false,
                            type = "CacheGen",
                        },
                    },
                    name = "ProductGen",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "gen",
                            optional = false,
                            type = "SchemaGen",
                        },
                        {
                            list = false,
                            name = "param",
                            optional = false,
                            type = "SchemaParam",
                        },
                        {
                            list = false,
                            name = "state",
                            optional = false,
                            type = "SchemaState",
                        },
                    },
                    name = "Schema",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = true,
                            name = "records",
                            optional = false,
                            type = "RecordGen",
                        },
                    },
                    name = "SchemaGen",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = true,
                            name = "records",
                            optional = false,
                            type = "Asdl2Lowered.Record",
                        },
                        {
                            list = true,
                            name = "sums",
                            optional = false,
                            type = "Asdl2Lowered.Sum",
                        },
                    },
                    name = "SchemaParam",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = true,
                            name = "arenas",
                            optional = false,
                            type = "Asdl2Lowered.ArenaSlot",
                        },
                        {
                            list = true,
                            name = "caches",
                            optional = false,
                            type = "Asdl2Lowered.CacheSlot",
                        },
                    },
                    name = "SchemaState",
                    unique = true,
                },
                {
                    fields = {},
                    name = "SingletonCache",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "key_arity",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "StructuralCache",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "parent_fqname",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "kind_name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "ctor",
                            optional = false,
                            type = "Asdl2Lowered.CtorFamily",
                        },
                        {
                            list = false,
                            name = "cache",
                            optional = false,
                            type = "CacheGen",
                        },
                    },
                    name = "VariantGen",
                    unique = false,
                },
            },
            sums = {
                {
                    name = "CacheGen",
                    variants = {
                        "NoCache",
                        "SingletonCache",
                        "StructuralCache",
                    },
                },
                {
                    name = "RecordGen",
                    variants = {
                        "ProductGen",
                        "VariantGen",
                    },
                },
            },
        },
        Asdl2Source = {
            records = {
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "BuiltinTypeRef",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = true,
                            name = "fields",
                            optional = false,
                            type = "Field",
                        },
                        {
                            list = false,
                            name = "unique_flag",
                            optional = false,
                            type = "boolean",
                        },
                    },
                    name = "Constructor",
                    unique = true,
                },
                {
                    fields = {},
                    name = "ExactlyOne",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "type_ref",
                            optional = false,
                            type = "TypeRef",
                        },
                        {
                            list = false,
                            name = "cardinality",
                            optional = false,
                            type = "Cardinality",
                        },
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "Field",
                    unique = true,
                },
                {
                    fields = {},
                    name = "Many",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = true,
                            name = "definitions",
                            optional = false,
                            type = "Definition",
                        },
                    },
                    name = "ModuleDef",
                    unique = false,
                },
                {
                    fields = {},
                    name = "Optional",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = true,
                            name = "fields",
                            optional = false,
                            type = "Field",
                        },
                        {
                            list = false,
                            name = "unique_flag",
                            optional = false,
                            type = "boolean",
                        },
                    },
                    name = "Product",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "fqname",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "QualifiedTypeRef",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = true,
                            name = "definitions",
                            optional = false,
                            type = "Definition",
                        },
                    },
                    name = "Spec",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = true,
                            name = "constructors",
                            optional = false,
                            type = "Constructor",
                        },
                        {
                            list = true,
                            name = "attribute_fields",
                            optional = false,
                            type = "Field",
                        },
                    },
                    name = "Sum",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "type_expr",
                            optional = false,
                            type = "TypeExpr",
                        },
                    },
                    name = "TypeDef",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "name",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "UnqualifiedTypeRef",
                    unique = false,
                },
            },
            sums = {
                {
                    name = "Cardinality",
                    variants = {
                        "ExactlyOne",
                        "Optional",
                        "Many",
                    },
                },
                {
                    name = "Definition",
                    variants = {
                        "ModuleDef",
                        "TypeDef",
                    },
                },
                {
                    name = "TypeExpr",
                    variants = {
                        "Product",
                        "Sum",
                    },
                },
                {
                    name = "TypeRef",
                    variants = {
                        "BuiltinTypeRef",
                        "UnqualifiedTypeRef",
                        "QualifiedTypeRef",
                    },
                },
            },
        },
        Asdl2Text = {
            records = {
                {
                    fields = {
                        {
                            list = false,
                            name = "text",
                            optional = false,
                            type = "string",
                        },
                    },
                    name = "Spec",
                    unique = true,
                },
            },
            sums = {},
        },
        Asdl2Token = {
            records = {
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "AttributesKw",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "Bar",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "Comma",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "Dot",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "Eof",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "Eq",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "text",
                            optional = false,
                            type = "string",
                        },
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "Ident",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "LBrace",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "LParen",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "ManyMark",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "ModuleKw",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "OptionalMark",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "RBrace",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "RParen",
                    unique = false,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "start_byte",
                            optional = false,
                            type = "number",
                        },
                        {
                            list = false,
                            name = "end_byte",
                            optional = false,
                            type = "number",
                        },
                    },
                    name = "Span",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = true,
                            name = "tokens",
                            optional = false,
                            type = "Token",
                        },
                    },
                    name = "Spec",
                    unique = true,
                },
                {
                    fields = {
                        {
                            list = false,
                            name = "span",
                            optional = false,
                            type = "Span",
                        },
                    },
                    name = "UniqueKw",
                    unique = false,
                },
            },
            sums = {
                {
                    name = "Token",
                    variants = {
                        "Ident",
                        "ModuleKw",
                        "AttributesKw",
                        "UniqueKw",
                        "Eq",
                        "Bar",
                        "OptionalMark",
                        "ManyMark",
                        "Comma",
                        "LParen",
                        "RParen",
                        "LBrace",
                        "RBrace",
                        "Dot",
                        "Eof",
                    },
                },
            },
        },
    },
    pipeline = {
        "Asdl2Text",
        "Asdl2Token",
        "Asdl2Source",
        "Asdl2Catalog",
        "Asdl2Lowered",
        "Asdl2Machine",
        "Asdl2LuaJIT",
    },
})
